### ISSUE TITLE
Error while training after many iterations

### ISSUE THREAD

**Issue by khiemledev** [mxin262/SwinTextSpotter#13]
After training for about 2000 iterations, I end up with this error:
![error-swintextspotter_2](https://user-images.githubusercontent.com/28501389/163153534-819d6b8e-ca83-439f-8663-a3ec7ffbf571.png)

**Comment by mxin262** [comment]
Please make sure the json file is right, especially the bbox. This problem may be caused by the the random crop and random rotation. You can try to set rotation angle to zero in [line 69](https://github.com/mxin262/SwinTextSpotter/blob/main/projects/SWINTS/swints/dataset_mapper.py), if your dataset does not contain curved text.
