### ISSUE TITLE
Empty instances during the training! 

### ISSUE THREAD

**Issue by miranmanesh** [mxin262/SwinTextSpotter#6]

**Comment by mxin262** [comment]
I did not encounter this problem. Could you provide some details?

**Comment by miranmanesh** [comment]
Here is the actuall error that happens and it is due to the empty instances
<img width="1792" alt="Screen Shot 2022-04-07 at 7 04 47 PM" src="https://user-images.githubusercontent.com/22510929/162348942-50e50469-93ca-460b-8eea-8029ee4d9912.png">

**Comment by mxin262** [comment]
Have you checked the label file? This problem may be caused by the the random crop and random rotation. You can try to set rotation angle to zero in [line 69](https://github.com/mxin262/SwinTextSpotter/blob/main/projects/SWINTS/swints/dataset_mapper.py), if your dataset does not contain curved text.

**Comment by mxin262** [comment]
Sorry, I find a bug in training code and i fix it now. I suggest you use the latest code to train the model.

**Comment by miranmanesh** [comment]
Thank you for your response!
